- name: vars-prompt
  hosts: localhost
  vars_prompt:
   - name: "user_name"
     prompt: "enter the username"
     private: no

   - name: "password"
     prompt: "enter the password"
     private: yes

  tasks:
   - name: print the information 
     ansible.builtin.debug:
     msg: "the username is {{ user_name }} and the password is {{ password }}"


#  - name: vars-prompt
#   hosts: localhost
#   vars_prompt:
#     - name: user_name
#       prompt: "Enter the username" # Changed "enter" to "Enter" for better style
#       private: no
#     - name: password
#       prompt: "Enter the password" # Changed "enter" to "Enter" for better style
#       private: yes

#   tasks:
#     - name: print the information
#       ansible.builtin.debug:
#         msg: "The username is {{ user_name }} and the password is {{ password }}" # Added "The" to the string, and corrected spacing.