- name: vars file
  hosts: localhost # Corrected "local host" to "localhost"

  tasks:
    - name: print  information
      vars:
        timings: "07:15 am"
      ansible.builtin.debug: # Corrected "ansible.bulitin.debug"
        msg: "we are learning {{ course }} and with {{ trainer }} and with {{ duration }}"