- name: data-types
  hosts: localhost
  vars:
    course: "devops with aws"
    tools:
      - ansible
      - docker
      - terraform
    experience:
      ansible: 2
      docker: 1
      aws: 1
      Realproject: true # Assuming "Realproject" is a boolean
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "we are learning {{ course }} and with {{ tools }} and with {{ experience }}"