- name: conditions
  hosts: localhost
  vars_prompt:
    - name: number
      prompt: "Please enter a number" # Improved prompt capitalization
      private: no
  tasks:
    - name: print number less than 10
      ansible.builtin.debug:
        msg: "The number is less than 10" # Improved message capitalization
      when: number < 10 # Added | int filter

    - name: print number greater than or equal to 10
      ansible.builtin.debug:
        msg: "The number is greater than or equal to 10" # Improved message capitalization
      when: number  > = 10