- name: default value
  hosts: localhost
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg: "Hello {{ course | default ('Ansible') }}"


- name: upper case
  hosts: localhost
  vars:
    greeting: "HELLO Good morning"
  tasks:
    - name: print upper case
      ansible.builtin.debug:
        msg: "Hello {{ greeting | upper }}"


- name: lower case
  hosts: localhost
  vars:
    greeting: "HELLO Good morning"
  tasks:
    - name: print lower case
      ansible.builtin.debug:
        msg: "Hello {{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,2,3,4,2,3,5,6,7,]
  tasks:
    - name: remove duplicates
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

- name: print min and max ages
  hosts: localhost
  vars:
    ages: [23, 45, 87, 98, 67]
  tasks:
    - name: print min and max ages
      ansible.builtin.debug:
        msg: "minages: {{ ages | min }} and maxages: {{ ages | max }}"

- name: convert dictionary into items/list
  hosts: localhost
  vars:
    my_dict: # this is called as dictionary or map or key/value pairs.
      Course: Ansbile
      Trainer: Sivakumar
      Duration: 120hr
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_dict }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_dict | dict2items }}"

      
- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'Course', 'value': 'Ansbile'}
    - {'key': 'Trainer', 'value': 'Sivakumar'}
    - {'key': 'Duration', 'value': '120hr'}
  tasks:
  - name: before convert
    ansible.builtin.debug:
      msg: "Before convert: {{ my_list }}"
  - name: after convert
    ansible.builtin.debug:
      msg: "After convert: {{ my_list | items2dict }}"