- name: default value
  hosts: localhost
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg: "Hello {{ course | default ('Ansible') }}"


- name: upper case
  hosts: localhost
  vars:
    greeting: "HELLO Good morning"
  tasks:
    - name: print upper case
      ansible.builtin.debug:
        msg: "Hello {{ greeting | upper }}"


- name: lower case
  hosts: localhost
  vars:
    greeting: "HELLO Good morning"
  tasks:
    - name: print lower case
      ansible.builtin.debug:
        msg: "Hello {{ greeting | lower }}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1,2,3,4,2,3,5,6,7,]
  tasks:
    - name: remove duplicates
      ansible.builtin.debug:
        msg: "{{ numbers | unique }}"

- name: print min and max ages
  hosts: localhost
  vars:
    ages: [23, 45, 87, 98, 67]
  tasks:
    - name: print min and max ages
      ansible.builtin.debug:
        msg: "minages: {{ ages | min }} and maxages: {{ ages | max }}"


- name: convert dictionary to items
  hosts: local host 
  vars:
    my-dict:
      course: "devops"
      trainer: "naresh"
      duration: "30 days"
  tasks:
    - name : convert to dictionary to items
      ansible.builtin.debug:
        msg: "{{ my-dict | dict2items}}"
  