- name: default value
  hosts: localhost
  tasks:
    - name: print default value
      ansible.builtin.debug:
        msg: "Hello {{ course | default ('Ansible') }}"


- name: upper case
  hosts: localhost
  vars:
    greeting: "HELLO Good morning"
  tasks:
    - name: print upper case
      ansible.builtin.debug:
        msg: "Hello {{ greeting | upper }}"