- name: demo on loops
  hosts: localhost
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: "{{ item }}" # Corrected "items" to "item"
      loop:
        - jenkins
        - ansible
        - docker



- name: downloading packages
  hosts: localhost
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.package: # Changed to the package module
        name: "{{ item }}"
        state: latest
      loop:
        - mysql
        - post fix 
        - nginx